# Generated by Django 5.1.2 on 2024-11-20 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0003_rename_file_name_submission_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Submissions',
        ),
    ]
