# Generated by Django 5.1.2 on 2024-11-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0005_usersubmitted_delete_submissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userSubmitted',
        ),
    ]
