# Generated by Django 5.1.2 on 2024-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0002_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='file_name',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='source_details',
            new_name='text_content',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='content',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
