# Generated by Django 5.1.2 on 2024-11-20 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0004_rename_submission_submissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plagiarism_percentage', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='userSubmitted/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
    ]
